steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/workright-hris-api', '--target', 'runtime-api', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/workright-hris-web', '--target', 'runtime-web', '.']

  # Push the container images to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workright-hris-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workright-hris-web']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'workright-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/workright-hris-api'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NODE_ENV=production,DATABASE_URL=$$DATABASE_URL,REDIS_URL=$$REDIS_URL'
    secretEnv: ['DATABASE_URL', 'REDIS_URL']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'workright-web'
      - '--image'
      - 'gcr.io/$PROJECT_ID/workright-hris-web'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_API_URL=$$API_URL'
    secretEnv: ['API_URL']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: 'DATABASE_URL'
    - versionName: projects/$PROJECT_ID/secrets/redis-url/versions/latest
      env: 'REDIS_URL'
    - versionName: projects/$PROJECT_ID/secrets/api-url/versions/latest
      env: 'API_URL'

images:
  - 'gcr.io/$PROJECT_ID/workright-hris-api'
  - 'gcr.io/$PROJECT_ID/workright-hris-web'
