options:
  env:
  - DOCKER_BUILDKIT=1
  - BUILDKIT_PROGRESS=plain
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
- name: gcr.io/cloud-builders/docker
  args: [build, --no-cache, -t, gcr.io/$PROJECT_ID/workright-hris-api, --target, runtime-api, .]

- name: gcr.io/cloud-builders/docker
  args:
  - build
  - --no-cache
  - -t
  - gcr.io/$PROJECT_ID/workright-hris-web
  - --target
  - runtime-web
  - --build-arg
  - NEXT_PUBLIC_API_URL=https://workright-api-932379746185.australia-southeast1.run.app
  - --build-arg
  - NEXT_PUBLIC_DEMO_MODE=true
  - --build-arg
  - NEXT_PUBLIC_TENANT_ID=demo-tenant-001
  - --build-arg
  - NEXT_PUBLIC_USER_ID=user-demo-admin
  - .

- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/workright-hris-api]

- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/workright-hris-web]

# API Deployment - FIXED: Added ALLOWED_ORIGINS for CORS
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - workright-api
  - --image=gcr.io/$PROJECT_ID/workright-hris-api
  - --region=australia-southeast1
  - --platform=managed
  - --allow-unauthenticated
  - --port=8080
  - --add-cloudsql-instances=workright-dev:australia-southeast1:hris-dev-db-d506
  - --set-env-vars=NODE_ENV=production,CLOUD_RUN=true,DEMO_MODE=true,ALLOWED_ORIGINS=https://workright-web-932379746185.australia-southeast1.run.app
  - --set-secrets=DATABASE_URL=database-url:latest
  - --timeout=300
  - --cpu=2
  - --memory=1Gi
  - --cpu-boost
  - --no-cpu-throttling
  - --max-instances=10
  - --min-instances=0

# Web Deployment
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - workright-web
  - --image=gcr.io/$PROJECT_ID/workright-hris-web
  - --region=australia-southeast1
  - --platform=managed
  - --allow-unauthenticated
  - --port=8080
  - --set-env-vars=NODE_ENV=production
  - --set-secrets=NEXT_PUBLIC_API_URL=api-url:latest
  - --timeout=300
  - --cpu=1
  - --memory=512Mi
  - --max-instances=10

images:
- gcr.io/$PROJECT_ID/workright-hris-api
- gcr.io/$PROJECT_ID/workright-hris-web
