cat > cloudbuild.yaml << 'EOF'
options:
  env:
  - DOCKER_BUILDKIT=1
  - BUILDKIT_PROGRESS=plain
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/workright-hris-api, --target, runtime-api, .]

- name: gcr.io/cloud-builders/docker
  args: [build, -t, gcr.io/$PROJECT_ID/workright-hris-web, --target, runtime-web, .]

- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/workright-hris-api]

- name: gcr.io/cloud-builders/docker
  args: [push, gcr.io/$PROJECT_ID/workright-hris-web]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - workright-api
  - --image=gcr.io/$PROJECT_ID/workright-hris-api
  - --region=australia-southeast1
  - --platform=managed
  - --allow-unauthenticated
  - --port=8080
  - --add-cloudsql-instances=workright-dev:australia-southeast1:hris-dev-db-d506
  - --set-env-vars=NODE_ENV=production,CLOUD_RUN=true
  - --set-env-vars=DATABASE_URL=$$DATABASE_URL
  - --timeout=300
  - --cpu=1
  - --memory=512Mi
  - --cpu-boost
  - --no-cpu-throttling
  - --max-instances=10
  - --min-instances=0
  secretEnv: [DATABASE_URL]

- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args:
  - run
  - deploy
  - workright-web
  - --image=gcr.io/$PROJECT_ID/workright-hris-web
  - --region=australia-southeast1
  - --platform=managed
  - --allow-unauthenticated
  - --port=8080
  - --set-env-vars=NODE_ENV=production
  - --set-env-vars=NEXT_PUBLIC_API_URL=$$API_URL
  - --timeout=300
  - --cpu=1
  - --memory=512Mi
  - --max-instances=10
  secretEnv: [API_URL]

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
    env: DATABASE_URL
  - versionName: projects/$PROJECT_ID/secrets/api-url/versions/latest
    env: API_URL

images:
- gcr.io/$PROJECT_ID/workright-hris-api
- gcr.io/$PROJECT_ID/workright-hris-web
EOF
