options:
  env:
    - DOCKER_BUILDKIT=1
    - BUILDKIT_PROGRESS=plain
  # Required when the trigger sets a build service account:
  # keeps logs in the same region as your build (AU-SE1).
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  # (Alternative minimal fix, if you prefer) logging: CLOUD_LOGGING_ONLY

steps:
  # Build API (runtime-api target)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/workright-hris-api', '--target', 'runtime-api', '.']

  # Build Web (runtime-web target)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['build', '-t', 'gcr.io/$PROJECT_ID/workright-hris-web', '--target', 'runtime-web', '.']

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workright-hris-api']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/workright-hris-web']

  # Deploy API to Cloud Run (listens on 8080)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','workright-api',
        '--image','gcr.io/$PROJECT_ID/workright-hris-api',
        '--region','australia-southeast1',
        '--platform','managed',
        '--allow-unauthenticated',
        '--set-env-vars','NODE_ENV=production,DATABASE_URL=$$DATABASE_URL,REDIS_URL=$$REDIS_URL'
      ]
    secretEnv: ['DATABASE_URL','REDIS_URL']

  # Deploy Web to Cloud Run (Next.js standalone on port 3000)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run','deploy','workright-web',
        '--image','gcr.io/$PROJECT_ID/workright-hris-web',
        '--region','australia-southeast1',
        '--platform','managed',
        '--allow-unauthenticated',
        '--port','3000',
        '--set-env-vars','NEXT_PUBLIC_API_URL=$$API_URL'
      ]
    secretEnv: ['API_URL']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/database-url/versions/latest
      env: DATABASE_URL
    - versionName: projects/$PROJECT_ID/secrets/redis-url/versions/latest
      env: REDIS_URL
    - versionName: projects/$PROJECT_ID/secrets/api-url/versions/latest
      env: API_URL

images:
  - 'gcr.io/$PROJECT_ID/workright-hris-api'
  - 'gcr.io/$PROJECT_ID/workright-hris-web'
